### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by marshall-davis** [jamfluencer/api#3]
We should probably start writing some tests so that I stop introducing regressions.

**Comment by pechtelt1** [comment]
@marshall-davis i would suggest to make use of PEST it is pretty easy to write test with that.

**Comment by marshall-davis** [comment]
Pest has some amazing features. I've not yet adjusted fully to to the style in which they layout tests; the testing API they provide. I know you can write class-based PHPUnit style tests with it. I haven't dug into how they provide some of the features and how I'd access them in PHPUnit style test. I would want to write Pest-like tests when using Pest.

It's certainly something I'd consider for this, and likely should.
